server:
  port: 8010
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yxzfyboy/spring-cloud/ # 配置git仓库的地址
          search-paths: config-repos # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: yxzfyboy  # git仓库的账号
          password: yxz123371381  # git仓库的密码
#        native:
#          search-locations: file:E:/properties/ #指定配置文件的位置
#  profiles:
#    active: native  #Spring Cloud Config也提供本地存储配置的方式