server:
  port: 7000
spring:
  application:
    name: zipkin-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8081/eureka/      #服务注册中心地址，含有BASIC认证的用户名和密码
#zipkin启动报错无法访问的解决方法
management:
  metrics:
    web:
      server:
        auto-time-requests: false