#服务消费者
server:
  port: 9101
spring:
  application:
    name: cloud-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8081/eureka/      #服务注册中心地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    # 状态页面和健康指标
#    statusPageUrlPath: ${server.servletPath}/info
#    healthCheckUrlPath: ${server.servletPat

# 熔断
feign:
  hystrix:
    enabled: true

logging:
  file: ./log/hystrix-dashboard.log #当前项目(指父工程)根目录

#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'